version: 2.1

description: |
  Common commands for Ruby on Rails setup, code hygiene, and security checks
  View this orb's source: https://github.com/Latermedia/circle-ci-ruby-rails-setup

jobs:
  build:
    working_directory: ~/firstproj
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run: gem update system
      - run: gem install bundler
      - run: bundler install
      #- run: rails s
      